.\" $Id$
.TH TURQSTAT 1 2001 "Softwolves Software" ""
.SH NAMN
turqstat \- Mötesstatistikprogram för Fidonet och Usenet
.SH SYNOPS
.PD 0
.B turqstat
[flaggor] utdatafil areadefinition(er)
.PD
.SH BESKRIVNING
.B Turquoise SuperStat
läser innehållet i en Fidonetmeddelandebas i något av de stödda formaten,
eller Usenetgrupper i det vanliga "news spool"-formatet, och skapar
statistik inom följande områden:
.RS
.PP
.I Svartlista över citatvolym.
.PP
.I Topplista över avsändare.
.PP
.I Topplista över originalinnehåll per meddelande.
.PP
.I Topplista över Fidonetnät (endast Fidonet).
.PP
.I Topplista över Internet-toppdomäner.
.PP
.I Topplista över mottagare (endast Fidonet).
.PP
.I Topplista över ärenderader.
.PP
.I Topplista över programvara.
.PP
.I Postningar per veckodag.
.PP
.I Postningar per tid på dygnet.
.RE
.PD
.SH FLAGGOR
.SS DATAURVAL
.TP
.I \-d dagar
Väljer det antal dagar tillbaka som meddelanden skall räknas från. Det
förinställda värdet är 0, vilket betyder att räkna alla meddelanden.
.TP
.I \-n antal
Väljer maximalt antal poster i topplistorna. Förinställt värde är 15. 0
anger att ingen gräns används.
.TP
.I \-r intervall
Väljer ett intervall av datum och tider för vilka statistik insamlas.
Intervallet anges på formen
.RI [ ååååmmdd [T hhmmss ]]\-[ ååååmmdd [T hhmmss ]].
Exempel:
.B 20000101T000000\-20001231T235959
är hela 2000,
.B \-20010101
är allting före (exklusive) 1 januari 2001, och
.B 20010101\-
är allting från (och med) 1 januari 2001.
.SS "VAL AV INDATA"
.TP
.I \-a sökväg
Väljer meddelandebassökväg för FXAPX/w-, MyPoint- och
tanstaaflmeddelandebaser, vilka har alla meddelandebaser i samma filer.
.TP
.I \-s
Squishmeddelandebaser (förval).
.TP
.I \-m
FTSC *.MSG-meddelandebaser.
.TP
.I \-o
OPUS *.MSG-meddelandebaser.
.TP
.I \-j
JAM-meddelandebaser.
.TP
.I \-f
FDAPX/w-meddelandebaser.
.TP
.I \-t
Tanstaaflmeddelandebaser.
.TP
.I \-p
MyPointmeddelandebaser.
.TP
.I \-u
Usenet news spool.
.SS "VAL AV TOPPLISTOR"
Dessa flaggor används för att stänga av topplistor.
Som förval är alla topplistor påslagna (förutom Internet-toppdomän, se
nedan).
.TP
.I \-Q
Stänger av citatvolymssvartlistan.
.TP
.I \-W
Stänger av avsändartopplistan.
.TP
.I \-O
Stänger av originalinnehållstopplista.
.TP
.I \-N
Stänger av nättopplistan (enbart Fidonet).
.TP
.I \-T
Stänger av/slår på topplistan över Internet-toppdomäner. För Usenet är
förval på, varpå denna flagga stänger av det. För Fidonet är förval av,
varpå denna flagga slår på det, men endast om RFC-gate:ade meddelanden
hittas.
.TP
.I \-R
Stänger av mottagartopplista (enbart Fidonet).
.TP
.I \-S
Stänger av ärenderadstopplista.
.TP
.I \-P
Stänger av programtopplista.
.TP
.I \-H
Stänger av postningsstatistik per timme.
.TP
.I \-D
Stänger av postningsstatistik per dag.
.TP
.I \-V
Stänger av visning av versioner i programtopplista.
.SS "UTSEENDE PÅ UTDATA"
.TP
.I \-A
Visar alla siffror i topplistorna (förinställt värde är av).
.TP
.I \-C teckenkodning
Väljer teckenkodning att använda för rapportfilerna som skapas.
Teckenkodningsnamnet kan anges med antingen dess Fidonet- eller dess
MIME-namn.
Förval för Win32- och OS/2-verisonen är IBMPC (teckentabell 437), och
för alla andra versioner LATIN-1 (iso-8859-1).
.TP
.I \-L
Använd datumformat enligt "locale"-defintion (förinställt värde är att
använda ISO-8601-format, vilket sammanfaller med EU- och svensk norm).
.SH "SE ÄVEN"
.BR turqstat (1),
.I turqstat.dok
.SH PROGRAMFEL
Rapportera eventuella fel till författaren.
.SH FÖRFATTARE
Turquoise SuperStat skrevs av Peter Karlsson.
Om du har felrapporter eller frågor, sänd e-post till
peter@softwolves.pp.se eller se webbplatsen på
http://www.softwolves.pp.se/sw/
.PP
A Softwolves Software (tm) Release in 2001.
.PP
Detta program är släppt enligt GNU General Public License, version 2.
