.\" $Id$
.TH TURQSTAT 1 "$Date$" "Softwolves Software" ""
.SH NAME
turqstat \- Statistics tool for Fidonet message bases
.SH SYNOPSIS
.PD 0
.B turqstat
[options] outputfile areadef(s)
.PD
.SH DESCRIPTION
.B Turquoise SuperStat
reads the contents of a Fidonet message area in one of its supported
formats, or a standard Usenet news spool, and creates statistics about this:
.RS
.PP
.I Quoter blacklist.
.PD 0
.PP
.I Toplist of senders.
.PP
.I Toplist of original content per message.
.PP
.I Toplist of receivers (Fidonet only).
.PP
.I Toplist of subjects.
.PP
.I Toplist of used software.
.PP
.I Postings by weekday.
.PP
.I Postings by time of day.
.RE
.PD
.SH OPTIONS
.SS "GENERAL OPTIONS"
.TP
.I \-d days
Selects the number of days back to count messages from. The default is
0, which mean count all messages.
.TP
.I \-n num
Selects the maximum number of entries in the toplists. The default is 15.
0 indicates no limit.
.TP
.I \-a path
Selects the area number for the FDAPX/w and MyPoint message bases, which
have all messages in the same files.
.SS "MESSAGE BASE TYPE"
.TP
.I \-s
Squish message bases (default).
.TP
.I \-m
FTSC *.MSG message bases.
.TP
.I \-o
OPUS *.MSG message bases.
.TP
.I \-j
JAM message bases.
.TP
.I \-f
FDAPX/w message bases.
.TP
.I \-t
Tanstaafl message bases.
.TP
.I \-p
MyPoint message bases.
.TP
.I \-u
Usenet news spool.
.SS "TOPLIST SELECTION"
These options are used to turn toplists off.
By default, all toplists are enabled.
.TP
.I \-Q
Turns the quoter blacklist off.
.TP
.I \-W
Turns the writer toplist off.
.TP
.I \-O
Turns the original content per message toplist off.
.TP
.I \-N
Turns the top nets (Fidonet only) list off.
.TP
.I \-R
Turns the recipient (Fidonet only) toplist off.
.TP
.I \-S
Turns the subject toplist off.
.TP
.I \-P
Turns the program toplist off.
.TP
.I \-H
Turns the hourly posting statistics off.
.TP
.I \-D
Turns the daily posting statistics off.
.TP
.I \-V
Turns the display of versions in the program toplist off.
.TP
.I \-A
Display all numbers in toplists (default is off).
.SH "SEE ALSO"
.I turqstat.doc
.SH BUGS
Report any bugs to the authors.
.SH AUTHOR
Turquoise SuperStat was written by Peter Karlsson.
If you have bug-reports or questions, mail them to
peter@softwolves.pp.se
.PP
A Softwolves Software (tm) Release in 2000.
.PP
This program is released under the GNU General Public License.
