.\" $Id$
.TH TURQSTAT 1 2001 "Softwolves Software" ""
.SH NAME
turqstat \- Statistics tool for Fidonet and Usenet
.SH SYNOPSIS
.PD 0
.B turqstat
[options] outputfile areadef(s)
.PD
.SH DESCRIPTION
.B Turquoise SuperStat
reads the contents of a Fidonet message area in one of its supported
formats, or a standard Usenet news spool, and creates statistics about this:
.RS
.PP
.I Quoter blacklist.
.PD 0
.PP
.I Toplist of senders.
.PP
.I Toplist of original content per message.
.PP
.I Toplist of Fidonet nets (Fidonet only).
.PP
.I Toplist of Internet topdomains.
.PP
.I Toplist of receivers (Fidonet only).
.PP
.I Toplist of subjects.
.PP
.I Toplist of used software.
.PP
.I Postings by weekday.
.PP
.I Postings by time of day.
.RE
.PD
.SH OPTIONS
.SS "DATA SELECTION"
.TP
.I \-d days
Selects the number of days back to count messages from. The default is
0, which mean count all messages.
.TP
.I \-n num
Selects the maximum number of entries in the toplists. The default is 15.
0 indicates no limit.
.TP
.I \-r range
Selects a range of dates and times for which statistics will be gathered.
The range is given on the form
.RI [ yyyymmdd [T hhmmss ]]\-[ yyyymmdd [T hhmmss ]].
Examples:
.B 20000101T000000\-20001231T235959
is all of 2000,
.B \-20010101
is everything before (not including) January 1st, 2001, and
.B 20010101\-
is everything from (and including) January 1st, 2001.
.SS "INPUT SELECTION"
.TP
.I \-a path
Selects the message base path for the FDAPX/w, MyPoint and taanstafl
message bases, which have all message bases in the same files.
.TP
.I \-s
Squish message bases (default).
.TP
.I \-m
FTSC *.MSG message bases.
.TP
.I \-o
OPUS *.MSG message bases.
.TP
.I \-j
JAM message bases.
.TP
.I \-f
FDAPX/w message bases.
.TP
.I \-t
Tanstaafl message bases.
.TP
.I \-p
MyPoint message bases.
.TP
.I \-u
Usenet news spool.
.SS "TOPLIST SELECTION"
These options are used to turn toplists off.
By default, all toplists are enabled (except for Internet top domains, see
below).
.TP
.I \-Q
Turns the quoter blacklist off.
.TP
.I \-W
Turns the writer toplist off.
.TP
.I \-O
Turns the original content per message toplist off.
.TP
.I \-N
Turns the top nets (Fidonet only) list off.
.TP
.I \-R
Turns the recipient (Fidonet only) toplist off.
.TP
.I \-T
Turns the top Internet topdomain list on/off. For Usenet, the default is
on, and this switch turns it off. For Fidonet, the default is off, and this
switch turns it on, but only if there are any RFC gated messages detected.
.TP
.I \-S
Turns the subject toplist off.
.TP
.I \-P
Turns the program toplist off.
.TP
.I \-H
Turns the hourly posting statistics off.
.TP
.I \-D
Turns the daily posting statistics off.
.TP
.I \-V
Turns the display of versions in the program toplist off.
.SS "OUTPUT OPTIONS"
.TP
.I \-A
Display all numbers in toplists (default is off).
.TP
.I \-C charset
Selects character encoding to use for the created report files.
The character encoding name can be specified by either its Fidonet or MIME
name.
Default for the Win32 and OS/2 versions is IBMPC (codepage 437), and
for all other versions LATIN-1 (iso-8859-1).
.TP
.I \-L
Use locale defined date format in output (default is ISO-8601 format, as
per Swedish and EU standards).
.SH "SEE ALSO"
.BR xturqstat (1),
.I turqstat.doc
.SH BUGS
Report any bugs to the authors.
.SH AUTHOR
Turquoise SuperStat was written by Peter Karlsson.
If you have bug reports or questions, mail them to
peter@softwolves.pp.se or see the website at
http://www.softwolves.pp.se/sw/
.PP
A Softwolves Software (tm) Release in 2001.
.PP
This program is released under the GNU General Public License, version 2.
