.\" $Id$
.TH TURQSTAT 1 2000 "Softwolves Software" ""
.SH NAMN
turqstat \- M”tesstatistikprogram f”r Fidonet och Usenet
.SH SYNOPSIS
.PD 0
.B turqstat
[flaggor] utdatafil areadefinition(er)
.PD
.SH BESKRIVNING
.B Turquoise SuperStat
l„ser inneh†llet i en Fidonetmeddelandebas i n†got av de st”dda formaten,
eller Usenetgrupper i det vanliga "news spool"-formatet, och skapar
statistik inom f”ljande omr†den:
.RS
.PP
.I Svartlista ”ver citatvolym.
.PP
.I Topplista ”ver avs„ndare.
.PP
.I Topplista ”ver originalinneh†ll per meddelande.
.PP
.I Topplista ”ver Fidonetn„t (endast Fidonet).
.PP
.I Topplista ”ver Internet-toppdom„ner.
.PP
.I Topplista ”ver mottagare (endast Fidonet).
.PP
.I Topplista ”ver „renderader.
.PP
.I Topplista ”ver programvara.
.PP
.I Postningar per veckodag.
.PP
.I Postningar per tid p† dygnet.
.RE
.PD
.SH FLAGGOR
.SS DATAURVAL
.TP
.I \-d dagar
V„ljer det antal dagar tillbaka som meddelanden skall r„knas fr†n. Det
f”rinst„llda v„rdet „r 0, vilket betyder att r„kna alla meddelanden.
.TP
.I \-n antal
V„ljer maximalt antal poster i topplistorna. F”rinst„llt v„rde „r 15. 0
anger att ingen gr„ns anv„nds.
.SS "VAL AV INDATA"
.TP
.I \-a s”kv„g
V„ljer meddelandebass”kv„g f”r FXAPX/w-, MyPoint- och
tanstaaflmeddelandebaser, vilka har alla meddelandebaser i samma filer.
.TP
.I \-s
Squishmeddelandebaser (f”rval).
.TP
.I \-m
FTSC *.MSG-meddelandebaser.
.TP
.I \-o
OPUS *.MSG-meddelandebaser.
.TP
.I \-j
JAM-meddelandebaser.
.TP
.I \-f
FDAPX/w-meddelandebaser.
.TP
.I \-t
Tanstaaflmeddelandebaser.
.TP
.I \-p
MyPointmeddelandebaser.
.TP
.I \-u
Usenet news spool.
.SS "VAL AV TOPPLISTOR"
Dessa flaggor anv„nds f”r att st„nga av topplistor.
Som f”rval „r alla topplistor p†slagna (f”rutom Internet-toppdom„n, se
nedan).
.TP
.I \-Q
St„nger av citatvolymssvartlistan.
.TP
.I \-W
St„nger av avs„ndartopplistan.
.TP
.I \-O
St„nger av originalinneh†llstopplista.
.TP
.I \-N
St„nger av n„ttopplistan (enbart Fidonet).
.TP
.I \-T
St„nger av/sl†r p† topplistan ”ver Internet-toppdom„ner. F”r Usenet „r
f”rval p†, varp† denna flagga st„nger av det. F”r Fidonet „r f”rval av,
varp† denna flagga sl†r p† det, men endast om RFC-gate:ade meddelanden
hittas.
.TP
.I \-R
St„nger av mottagartopplista (enbart Fidonet).
.TP
.I \-S
St„nger av „renderadstopplista.
.TP
.I \-P
St„nger av programtopplista.
.TP
.I \-H
St„nger av postningsstatistik per timme.
.TP
.I \-D
St„nger av postningsstatistik per dag.
.TP
.I \-V
St„nger av visning av versioner i programtopplista.
.SS "UTSEENDE P UTDATA"
.TP
.I \-A
Visar alla siffror i topplistorna (f”rinst„llt v„rde „r av).
.TP
.I \-L
Anv„nd datumformat enligt "locale"-defintion (f”rinst„llt v„rde „r att
anv„nda ISO-8601-format, vilket sammanfaller med EU- och svensk norm).
.SH "SE VEN"
.I turqstat.dok
.SH BUGS
Eftersom C-bibliotek k„nner av tidszoner f”rekommer det flera platser d„r
tider p† grund av detta kan feltolkas.
Detta „r inte ett fel i programmet, utan ett fel i definitionen av
programmeringsspr†ket C.
Se dokumentationsfilen n„mnd ovan f”r vidare information.
.PP
Rapportera eventuella fel till f”rfattaren.
.SH AUTHOR
Turquoise SuperStat skrevs av Peter Karlsson.
Om du har felrapporter eller fr†gor, s„nd e-post till
peter@softwolves.pp.se eller se webbplatsen p†
http://www.softwolves.pp.se/
.PP
A Softwolves Software (tm) Release in 2000.
.PP
Detta program „r sl„ppt enligt GNU General Public License, version 2.
