.TH XTURQSTAT 1 2001 "Softwolves Software" ""
.SH NAME
xturqstat \- Statistics tool for Fidonet and Usenet
.SH SYNOPSIS
.PD 0
.B xturqstat
.PD
.SH DESCRIPTION
.B Turquoise SuperStat
reads the contents of a Fidonet message area in one of its supported
formats, or a standard Usenet news spool, and creates statistics about this:
.RS
.PP
.I Quoter blacklist.
.PD 0
.PP
.I Toplist of senders.
.PP
.I Toplist of original content per message.
.PP
.I Toplist of Fidonet nets (Fidonet only).
.PP
.I Toplist of Internet topdomains.
.PP
.I Toplist of receivers (Fidonet only).
.PP
.I Toplist of subjects.
.PP
.I Toplist of used software.
.PP
.I Postings by weekday.
.PP
.I Postings by time of day.
.RE
.PD
.SH "SEE ALSO"
.BR turqstat (1),
.I turqstat.doc
.SH BUGS
Report any bugs to the authors.
.SH AUTHOR
Turquoise SuperStat was written by Peter Karlsson.
If you have bug reports or questions, mail them to
peter@softwolves.pp.se or see the website at
http://www.softwolves.pp.se/sw/
.PP
A Softwolves Software (tm) Release in 2008.
.PP
This program is released under the GNU General Public License, version 2.
