.TH XTURQSTAT 1 2008 "Softwolves Software" ""
.SH NAMN
xturqstat \- Mötesstatistikprogram för Fidonet och Usenet
.SH SYNOPS
.PD 0
.B xturqstat
.PD
.SH BESKRIVNING
.B Turquoise SuperStat
läser innehållet i en Fidonetmeddelandebas i något av de stödda formaten,
eller Usenetgrupper i det vanliga "news spool"-formatet, och skapar
statistik inom följande områden:
.RS
.PP
.I Svartlista över citatvolym.
.PP
.I Topplista över avsändare.
.PP
.I Topplista över originalinnehåll per meddelande.
.PP
.I Topplista över Fidonetnät (endast Fidonet).
.PP
.I Topplista över Internet-toppdomäner.
.PP
.I Topplista över mottagare (endast Fidonet).
.PP
.I Topplista över ärenderader.
.PP
.I Topplista över programvara.
.PP
.I Postningar per veckodag.
.PP
.I Postningar per tid på dygnet.
.RE
.PD
.SH "SE ÄVEN"
.BR turqstat (1),
.I turqstat.dok
.SH PROGRAMFEL
Rapportera eventuella fel till författaren.
.SH FÖRFATTARE
Turquoise SuperStat skrevs av Peter Karlsson.
Om du har felrapporter eller frågor, sänd e-post till
peter@softwolves.pp.se eller se webbplatsen på
http://www.softwolves.pp.se/sw/
.PP
A Softwolves Software (tm) Release in 2008.
.PP
Detta program är släppt enligt GNU General Public License, version 2.
