.\" $Id$
.TH XTURQSTAT 1 2000 "Softwolves Software" ""
.SH NAMN
xturqstat \- M”tesstatistikprogram f”r Fidonet och Usenet
.SH SYNOPS
.PD 0
.B xturqstat
.PD
.SH BESKRIVNING
.B Turquoise SuperStat
l„ser inneh†llet i en Fidonetmeddelandebas i n†got av de st”dda formaten,
eller Usenetgrupper i det vanliga "news spool"-formatet, och skapar
statistik inom f”ljande omr†den:
.RS
.PP
.I Svartlista ”ver citatvolym.
.PP
.I Topplista ”ver avs„ndare.
.PP
.I Topplista ”ver originalinneh†ll per meddelande.
.PP
.I Topplista ”ver Fidonetn„t (endast Fidonet).
.PP
.I Topplista ”ver Internet-toppdom„ner.
.PP
.I Topplista ”ver mottagare (endast Fidonet).
.PP
.I Topplista ”ver „renderader.
.PP
.I Topplista ”ver programvara.
.PP
.I Postningar per veckodag.
.PP
.I Postningar per tid p† dygnet.
.RE
.PD
.SH "SE ŽVEN"
.BR turqstat (1),
.I turqstat.dok
.SH PROGRAMFEL
Rapportera eventuella fel till f”rfattaren.
.SH F™RFATTARE
Turquoise SuperStat skrevs av Peter Karlsson.
Om du har felrapporter eller fr†gor, s„nd e-post till
peter@softwolves.pp.se eller se webbplatsen p†
http://www.softwolves.pp.se/
.PP
A Softwolves Software (tm) Release in 2000.
.PP
Detta program „r sl„ppt enligt GNU General Public License, version 2.
